/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.view;

import com.coderbd.dao.ProductDao;
import com.coderbd.dao.SummaryDao;
import com.coderbd.daoImpl.ProductDaoImpl;
import com.coderbd.daoImpl.SummaryDaoImpl;
import com.coderbd.pojo.Product;
import com.coderbd.pojo.Summary;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author User
 */
public class ProductView extends javax.swing.JFrame {

    /**
     * Creates new form ProductView
     */
    public ProductView() {
        initComponents();
        displayIntoProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void createTable() {
        DefaultTableModel model = (DefaultTableModel) tblDisplayProduct.getModel();
        model.setNumRows(0);
    }

    public void displayIntoProduct() {
        createTable();
        ProductDao pdao = new ProductDaoImpl();
        List<Product> list = pdao.getList();
        DefaultTableModel model = (DefaultTableModel) tblDisplayProduct.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getProductName();
            row[2] = list.get(i).getQuantity();
            row[3] = list.get(i).getUnitPrice();
            row[4] = list.get(i).getTotalPrice();
            model.addRow(row);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayProduct = new javax.swing.JTable();
        btnPurches = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProcudtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayProduct.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "ID", "Product Name", "Quantity", "Unit Price", "Total Price"
                }
        ));
        tblDisplayProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayProductMouseClicked(evt);
            }
        });
        tblDisplayProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDisplayProductKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayProduct);

        btnPurches.setText("Purches");
        btnPurches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchesActionPerformed(evt);
            }
        });

        jLabel1.setText("Product Name");

        jLabel2.setText("Quantity");

        txtUnitPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnitPriceKeyReleased(evt);
            }
        });

        jLabel3.setText("Unit Price");

        jLabel4.setText("Total Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(334, 334, 334)
                                                .addComponent(btnPurches))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtProcudtName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtProcudtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnPurches)
                                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPurchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchesActionPerformed
        // TODO add your handling code here:

        ProductDao productDao = new ProductDaoImpl();
        Product product = new Product(txtProcudtName.getText().trim(), Integer.parseInt(txtQuantity.getText().trim()), Double.parseDouble(txtUnitPrice.getText().trim()), Double.parseDouble(txtTotalPrice.getText().trim()));
        productDao.save(product);
        displayIntoProduct();

        SummaryDao summaryDao = new SummaryDaoImpl();
        try {
            Summary summary = summaryDao.getProductByName(txtProcudtName.getText().trim());

            if (summary.getProductName() != null) {

                int quantity = summary.getQuantity() + Integer.parseInt(txtQuantity.getText().trim());
                double availableqty = summary.getAvailabe() + Integer.parseInt(txtQuantity.getText().trim());

                Summary summaryUp = new Summary(summary.getProductName(), quantity, summary.getUnitPrice(), summary.getTotalPrice(), availableqty, summary.getSoldQty());
                summaryDao.update(summaryUp);
                JOptionPane.showMessageDialog(null, "Purchase Again success");
            } else {
                
                
               /*
                Product product1 = productDao.getProductByProductCode(product.getProductCode());
                Summary summary2 = new Summary(txtProName.getText().trim(), txtProCode.getText().trim(), Integer.parseInt(txtQty.getText().trim()), 0, Integer.parseInt(txtQty.getText().trim()), product1);
                summaryDao.save(summary2);
                JOptionPane.showMessageDialog(null, "Purchase success");
        */
                Product product1 = productDao.getProductByName(product.getProductName());
                Summary summary2 = new Summary(txtProcudtName.getText().trim(), Integer.parseInt(txtQuantity.getText().trim()), Integer.parseInt(txtUnitPrice.getText().trim()), Double.parseDouble(txtTotalPrice.getText().trim()));
                summaryDao.save(summary2);
                JOptionPane.showMessageDialog(null, "Purchase success");

            }

        } catch (Exception e) {
            e.printStackTrace();
            Product product1 = productDao.getProductByName(product.getProductName());
            Summary summary2 = new Summary(txtProcudtName.getText().trim(), Integer.parseInt(txtQuantity.getText().trim()), Double.parseDouble(txtUnitPrice.getText().trim()), Integer.parseInt(txtTotalPrice.getText().trim()));
            summaryDao.save(summary2);
            JOptionPane.showMessageDialog(null, "Purchase success");
        }
        displayIntoProduct();
    }//GEN-LAST:event_btnPurchesActionPerformed


    private void txtUnitPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitPriceKeyReleased
        // TODO add your handling code here:
        int quantity = Integer.parseInt(txtQuantity.getText().trim());
        double unitPrice = Double.parseDouble(txtUnitPrice.getText().trim());
        double totalPrice = quantity * unitPrice;
        txtTotalPrice.setText(totalPrice + "");


    }//GEN-LAST:event_txtUnitPriceKeyReleased

    private void tblDisplayProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDisplayProductKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDisplayProductKeyReleased

    private void tblDisplayProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayProductMouseClicked
        // TODO add your handling code here:
        int i = tblDisplayProduct.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblDisplayProduct.getModel();
        txtProcudtName.setText(model.getValueAt(i, 1).toString());
        txtQuantity.setText(model.getValueAt(i, 2).toString());
        txtUnitPrice.setText(model.getValueAt(i, 3).toString());
        txtTotalPrice.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tblDisplayProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurches;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayProduct;
    private javax.swing.JTextField txtProcudtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
